# Generated by Django 5.2.11 on 2026-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugMonograph',
            fields=[
                ('key_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ten_hoat_chat', models.TextField(blank=True, null=True)),
                ('ten_chung_quoc_te', models.TextField(blank=True, null=True)),
                ('ten_thuong_mai', models.TextField(blank=True, null=True)),
                ('ma_atc', models.CharField(blank=True, max_length=100, null=True)),
                ('chong_chi_dinh', models.TextField(blank=True, null=True)),
                ('than_trong', models.TextField(blank=True, null=True)),
                ('tuong_tac_thuoc', models.TextField(blank=True, null=True)),
                ('cac_truong_hop_cu_the', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
